#!/bin/bash

nat=$(grep nat espresso.pwi | awk '{print $NF}')
fixed=$(grep ATOMIC_POSITIONS -A $nat espresso.pwi | grep '[A-Z]*[0-9]' | grep "0 0 0" -n | awk -F  ':' '{print $1}')
not_fixed=$(grep ATOMIC_POSITIONS -A $nat espresso.pwi | grep '[A-Z]*[0-9]' | grep -v "0 0 0" -n | awk -F  ':' '{print $1}')

#TEST
echo FIXED $fixed
echo NOT FIXED $not_fixed

tmpsteps=$(grep -c Force espresso.pwo)
nat1=$((nat+1))
natlast=$((3*nat))
#nat2=$((tmpsteps*nat))

echo $nat Atoms

declare -a fx #=( "$@" )

fx=($(grep Forces espresso.pwo -A $nat1 | grep "atom " | sed 's/-//g' | awk '{print $7}' | tail -n $natlast ))
fy=($(grep Forces espresso.pwo -A $nat1 | grep "atom " | sed 's/-//g' | awk '{print $8}' | tail -n $natlast ))
fz=($(grep Forces espresso.pwo -A $nat1 | grep "atom " | sed 's/-//g' | awk '{print $9}' | tail -n $natlast ))

#echo ${fx[1]}
length=$(echo "${#fx[@]}")
echo $length forces
steps=$((${#fx[@]}/$nat))
echo $steps last steps

j=0
step=1
maxxforce=0
maxyforce=0
maxzforce=0
for i in $(eval echo "{0..$(($length))}");do
  j=$((j+1))
  if [ $j -ge $nat1 ];then
    j=1
    echo Step $step Max Delta Force $maxxforce $maxyforce $maxzforce Bohr/Ry
    maxxforce=0
    maxyforce=0
    maxzforce=0
    step=$((step+1))
  fi
  if (echo "$fixed" | fgrep -q "$j");then
    k=0
    #echo $j fixed
  else
    diffxormat=$(echo ${fx[$i]} | awk '{printf "%1.9f",$1}')
    if (( $(echo $diffxormat '>' $maxxforce | bc -l) ));then
      maxxforce=$diffxormat
    fi
    diffyormat=$(echo ${fy[$i]} | awk '{printf "%1.9f",$1}')
    if (( $(echo $diffyormat '>' $maxyforce | bc -l) ));then
      maxyforce=$diffyormat
    fi
    diffzormat=$(echo ${fz[$i]} | awk '{printf "%1.9f",$1}')
    if (( $(echo $diffzormat '>' $maxzforce | bc -l) ));then
      maxzforce=$diffzormat
    fi
  fi
done

